spring.application.name=tlias
spring.datasource.url=jdbc:mysql://root:75stnzlq@dbconn.sealoshzh.site:48092/mydatabase
spring.datasource.password=75stnzlq
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.servlet.context-path=/api
#server.tomcat.connection-timeout=600000
mybatis-plus.configuration.map-underscore-to-camel-case=true
server.port=8080
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath:/*.xml
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
# 静态资源访问路径
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${user.dir}/uploads/
# 文件保存路径
file.upload.path=${user.dir}/uploads/


